<?xml version = "1.0" encoding="UTF-8"?>
<!DOCTYPE TEI [
    <!ELEMENT TEI (header, facsimile?, testo+) >
    <!ELEMENT header (#PCDATA) >
    <!ELEMENT facsimile (#PCDATA) >
    <!ELEMENT testo (#PCDATA | seg)* >
    <!ELEMENT seg (#PCDATA) >

    <!ATTLIST header type CDATA #FIXED "intestazione" >
    <!ATTLIST header lang NMTOKEN #IMPLIED >
    <!ATTLIST facsimile source CDATA #REQUIRED >
    <!ATTLIST facsimile ref IDREFS #IMPLIED >
    <!ATTLIST testo id ID #REQUIRED >
    <!ATTLIST testo type CDATA #IMPLIED >
]>

<TEI>
    <header> header </header>
    <facsimile source="source"> facsimile </facsimile>
    <testo id="uno"> testo1 </testo>
    <testo id="due"> 
        <seg>seg</seg> 
    </testo>
</TEI>